In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = sns.load_dataset("titanic")

In [ ]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [ ]:
df.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
df.drop(["deck","embark_town","alive","class","who","adult_male"],axis = 1,inplace = True)

In [ ]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S  False
1         1       1  female  38.0      1      0  71.2833        C  False
2         1       3  female  26.0      0      0   7.9250        S   True
3         1       1  female  35.0      1      0  53.1000        S  False
4         0       3    male  35.0      0      0   8.0500        S   True

In [ ]:
df['age'].fillna(df['age'].mean(),inplace = True)

/tmp/ipykernel_2887/240904280.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].mean(),inplace = True)

In [ ]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S  False
1         1       1  female  38.0      1      0  71.2833        C  False
2         1       3  female  26.0      0      0   7.9250        S   True
3         1       1  female  35.0      1      0  53.1000        S  False
4         0       3    male  35.0      0      0   8.0500        S   True

In [ ]:
df.dropna(subset=["embarked"],inplace = True)

In [ ]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S  False
1         1       1  female  38.0      1      0  71.2833        C  False
2         1       3  female  26.0      0      0   7.9250        S   True
3         1       1  female  35.0      1      0  53.1000        S  False
4         0       3    male  35.0      0      0   8.0500        S   True

In [ ]:
df.isna().sum()

survived    0
pclass      0
sex         0
age         0
sibsp       0
parch       0
fare        0
embarked    0
alone       0
dtype: int64

In [ ]:
df['alone'] = df['alone'].astype(int)

In [ ]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S      0
1         1       1  female  38.0      1      0  71.2833        C      0
2         1       3  female  26.0      0      0   7.9250        S      1
3         1       1  female  35.0      1      0  53.1000        S      0
4         0       3    male  35.0      0      0   8.0500        S      1

In [ ]:
df['sex'] = df['sex'].map({"male":0,"female":1})

In [ ]:
df.head()

   survived  pclass  sex   age  sibsp  parch     fare embarked  alone
0         0       3    0  22.0      1      0   7.2500        S      0
1         1       1    1  38.0      1      0  71.2833        C      0
2         1       3    1  26.0      0      0   7.9250        S      1
3         1       1    1  35.0      1      0  53.1000        S      0
4         0       3    0  35.0      0      0   8.0500        S      1

In [ ]:
df = pd.get_dummies(df,columns = ["embarked"])

In [ ]:
df['embarked_C'] = df['embarked_C'].astype(int)
df['embarked_Q'] = df['embarked_Q'].astype(int)
df['embarked_S'] = df['embarked_S'].astype(int)

In [ ]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,alone,embarked_C,embarked_Q,embarked_S
0,0,3,0,22.0,1,0,7.2500,0,0,0,1
1,1,1,1,38.0,1,0,71.2833,0,1,0,0
2,1,3,1,26.0,0,0,7.9250,1,0,0,1
3,1,1,1,35.0,1,0,53.1000,0,0,0,1
4,0,3,0,35.0,0,0,8.0500,1,0,0,1

In [ ]:
x = df.drop(['survived'],axis = 1)
y = df['survived']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=42)

Logistic regression

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
y_pred = model.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

accuracy_score(y_test,y_pred)

0.8089887640449438

In [ ]:
confusion_matrix(y_test,y_pred)

array([[91, 18],
       [16, 53]])

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.75      0.77      0.76        69

    accuracy                           0.81       178
   macro avg       0.80      0.80      0.80       178
weighted avg       0.81      0.81      0.81       178

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [ ]:
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.fit_transform(x_test)

KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier(n_neighbors = 5)
knn_model.fit(x_train_scaled,y_train)

KNeighborsClassifier()

In [ ]:
y_pred_knn = knn_model.predict(x_test_scaled)

In [ ]:
accuracy_score(y_test,y_pred_knn)

0.7865168539325843

In [ ]:
print(classification_report(y_test,y_pred_knn))

              precision    recall  f1-score   support

           0       0.84      0.81      0.82       109
           1       0.71      0.75      0.73        69

    accuracy                           0.79       178
   macro avg       0.78      0.78      0.78       178
weighted avg       0.79      0.79      0.79       178

navie bayes algorithm

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
navie_model = GaussianNB()

navie_model.fit(x_train,y_train)

GaussianNB()

In [ ]:
y_pred_navie = navie_model.predict(x_test)

In [ ]:
accuracy_score(y_test,y_pred_navie)

0.7528089887640449

In [ ]:
print(classification_report(y_test,y_pred_navie))

              precision    recall  f1-score   support

           0       0.84      0.74      0.79       109
           1       0.65      0.77      0.71        69

    accuracy                           0.75       178
   macro avg       0.74      0.76      0.75       178
weighted avg       0.76      0.75      0.76       178

decision tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier

model_desicion_tree = DecisionTreeClassifier()

In [ ]:
model_desicion_tree.fit(x_train_scaled,y_train)

DecisionTreeClassifier()

In [ ]:
y_pred_dt = model_desicion_tree.predict(x_test_scaled)

In [ ]:
accuracy_score(y_test,y_pred_dt)

0.6966292134831461

In [ ]:
print(classification_report(y_test,y_pred_dt))

              precision    recall  f1-score   support

           0       0.78      0.70      0.74       109
           1       0.59      0.70      0.64        69

    accuracy                           0.70       178
   macro avg       0.69      0.70      0.69       178
weighted avg       0.71      0.70      0.70       178

Support vector machine (SVM)

In [ ]:
from sklearn.svm import SVC
model_svc = SVC(kernel = 'rbf')
model_svc.fit(x_train_scaled,y_train)

SVC()

In [ ]:
y_pred_svc = model_svc.predict(x_test_scaled)

In [ ]:
accuracy_score(y_test,y_pred_svc)

0.8314606741573034

In [ ]:
print(classification_report(y_test,y_pred_svc))

              precision    recall  f1-score   support

           0       0.85      0.88      0.86       109
           1       0.80      0.75      0.78        69

    accuracy                           0.83       178
   macro avg       0.82      0.82      0.82       178
weighted avg       0.83      0.83      0.83       178

In [ ]:
confusion_matrix(y_test,y_pred_svc)

array([[96, 13],
       [17, 52]])

cross valiadition

In [ ]:
from sklearn.model_selection import cross_val_score

x_train = df.drop('survived',axis = 1)
y = df['survived']

x_train_scaled = scaler.fit_transform(x_train)

scores = cross_val_score(model_svc, x_train_scaled, y, cv = 5, scoring = 'accuracy')

In [ ]:
print(scores)

[0.83707865 0.81460674 0.81460674 0.79775281 0.87570621]

In [ ]:
print(scores.mean())

0.8279502317018981